import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW


import runnerPackage.Runner_Assessment_other_nonbillable

CucumberKW.runWithCucumberRunner(Runner_Assessment_other_nonbillable.class)

